// For local dev
// export const rootUrl = "http://localhost:8000"
// export const rtsUrl = "http://localhost:5000"
// export const userAuthToken = "eyJ0b2tlbiI6IjA4YTQ5YzgxLTA1YWQtNDBjNC05MWY2LTkxZDI4NTcyJDA4YTQ5YzgxLTA1YWQtNDBjNC05MWY2LTkxZDI4NTcyZjI0NzQ4MGM1N2YxLWE2YTMtNDc5My1hMDZhLTQ0NTVhMWY2NGUxMiIsImdhdGV3YXkiOiJNb3ppbGxhLzUuMCAoTWFjaW50b3NoOyBJbnRlbCBNYWMgT1MgWCAxMF8xMl82KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvNjEuMC4zMTYzLjEwMCBTYWZhcmkvNTM3LjM2In0:1e0WIE:dG-MKp17i_9bZ5bh-HOLyq0bJHg"

// For dev environment, uncomment
export const rootUrl = "https://dev.humandx.org"
export const rtsUrl = "https://dev-socket.humandx.org"
export const userAuthToken = "eyJ0b2tlbiI6IjYxNTE0ZmY3LWViNzItNDg1NS05YzNlLTg2Njk4ZmExJDYxNTE0ZmY3LWViNzItNDg1NS05YzNlLTg2Njk4ZmExNTYxM2FiZjRiZjQzLThmYmEtNGIyZi05ODdlLWJiYjI3ZTNmYzlmNCIsImdhdGV3YXkiOiJNb3ppbGxhLzUuMCAoTWFjaW50b3NoOyBJbnRlbCBNYWMgT1MgWCAxMF8xMl82KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvNjEuMC4zMTYzLjEwMCBTYWZhcmkvNTM3LjM2In0:1dzpTl:ZcwmQ96pZam-Dbaamhy7VrtfMQM"
